def perform_inference(agent, input_data):
    """
    Perform inference using the provided agent and input data.

    Parameters:
    agent (BaseAgent): The agent to use for inference.
    input_data (dict): The input data for the inference process.

    Returns:
    dict: The output generated by the agent after processing the input data.
    """
    # Analyze the request using the agent
    analysis = agent.analyze_request(input_data)

    # Select the appropriate tool based on the analysis
    tool = agent.select_tool(analysis)

    # Use the selected tool to perform inference
    output = tool.perform_inference(analysis)

    return output

def batch_inference(agents, input_data_list):
    """
    Perform batch inference using a list of agents and input data.

    Parameters:
    agents (list): A list of agents to use for inference.
    input_data_list (list): A list of input data dictionaries for the inference process.

    Returns:
    list: A list of outputs generated by the agents after processing the input data.
    """
    outputs = []
    for input_data in input_data_list:
        for agent in agents:
            output = perform_inference(agent, input_data)
            outputs.append(output)
    return outputs